```yaml id="0kkqax"
name: Deploy Static Website

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout muacloud.github.io
        uses: actions/checkout@v4
        with:
          repository: muacloud/muacloud.github.io
          path: site

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-east-1

      - name: Sync to S3
        run: |
          aws s3 sync ./site s3://${{ secrets.AWS_S3_BUCKET }} \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "README.md"

          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }} s3://${{ secrets.AWS_S3_BUCKET }} \
            --recursive \
            --exclude "*" \
            --include "*.html" \
            --metadata-directive REPLACE \
            --content-type "text/html"

          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }} s3://${{ secrets.AWS_S3_BUCKET }} \
            --recursive \
            --exclude "*" \
            --include "*.css" \
            --metadata-directive REPLACE \
            --content-type "text/css"

          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }} s3://${{ secrets.AWS_S3_BUCKET }} \
            --recursive \
            --exclude "*" \
            --include "*.js" \
            --metadata-directive REPLACE \
            --content-type "application/javascript"

      - name: Create CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
```
