```yaml id="bwzj2y"
name: Deploy Static Website

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '*/5 * * * *'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # 拉取 muacloud.github.io 仓库
      - name: Checkout muacloud.github.io
        uses: actions/checkout@v4
        with:
          repository: muacloud/muacloud.github.io
          path: site

      # AWS 登录
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-east-1

      # 上传到 S3
      - name: Sync to S3
        run: |

          aws s3 sync ./site s3://${{ secrets.AWS_S3_BUCKET }} \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "README.md"

          # 修正 HTML MIME
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }} s3://${{ secrets.AWS_S3_BUCKET }} \
            --recursive \
            --exclude "*" \
            --include "*.html" \
            --metadata-directive REPLACE \
            --content-type "text/html"

          # 修正 CSS MIME
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }} s3://${{ secrets.AWS_S3_BUCKET }} \
            --recursive \
            --exclude "*" \
            --include "*.css" \
            --metadata-directive REPLACE \
            --content-type "text/css"

          # 修正 JS MIME
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }} s3://${{ secrets.AWS_S3_BUCKET }} \
            --recursive \
            --exclude "*" \
            --include "*.js" \
            --metadata-directive REPLACE \
            --content-type "application/javascript"

      # 刷新 CloudFront 缓存
      - name: Create CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
```
